#!/usr/bin/env python

#
# This script is a part of 'dsat' project by Dmitry Dulepov.
#
# @see https://github.com/dmitryd/dsat/
#

import sys

def checkVersionAndExit():
    """
    Checks python version and dies if the version is not right.
    """
    if sys.version_info < (2,7) or sys.version_info > (2,7,9999):
        print 'Use python 2.7, with dsat, please.'
        exit()

checkVersionAndExit()
