#!/usr/bin/env python

#
# This script is a part of 'dsat' project by Dmitry Dulepov.
#
# @see https://github.com/dmitryd/dsat/
#

import inspect
import sys

def actionDirdiff():
    import dirdiff
    dirdiff.run()

def actionHelp():
    """
    Shows help.
    """
    print "Usage: dsat action [action-options ...]"
    print ""
    print "For help on each action options, use dsat action -h"
    print ""
    print "Valid actions:"
    functionNames = [ name for name,obj in inspect.getmembers(sys.modules[__name__]) if inspect.isfunction(obj) ]
    for functionName in functionNames:
        if functionName[0:6] == 'action':
            actionName = functionName[6:]
            print "  " + actionName[0].lower() + actionName[1:]



def errorActionNotFound(action):
    """
    Acts when the action is not found
    """
    print "Error: Action %s not found" % action
    print "dsat -h for help"

def checkVersionAndExit():
    """
    Checks python version and dies if the version is not right.
    """
    if sys.version_info < (2,7) or sys.version_info > (2,7,9999):
        print 'Use python 2.7, with dsat, please.'
        exit()


def parseAction():
    """
    Parses arguments and returns them or shows usage and dies if no argument found.
    """
    if len(sys.argv) >= 2:
        action = sys.argv[1]
    else:
        action = 'help'
    return action

checkVersionAndExit()
action = parseAction()
actionMethod = 'action' + action[0].upper() + action[1:];

try:
    eval(actionMethod + "()")
except NameError:
    errorActionNotFound(action)
